# Generated by Django 4.2.5 on 2023-09-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='preview',
            field=models.ImageField(blank=True, default='avatars/avatar.png', null=True, upload_to='direction/preview', verbose_name='изображение'),
        ),
    ]
