# Generated by Django 4.2.5 on 2023-09-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_direction_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_days',
        ),
    ]
