# Generated by Django 4.2.5 on 2023-09-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_order_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена'),
        ),
    ]
